/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 audiA8.gltf 
Author: everhard (https://sketchfab.com/everhard)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/audi-a8-custom-2018-cd094d03f7684809900a929a9c88c8db
Title: Audi A8 Custom 2018
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei' 
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three'; 

export default function Model(props) {
  const { nodes, materials } = useGLTF('/audiA8.gltf')
  if(props.material != "null"){
    const galaxyTexture = useLoader(TextureLoader, props.material);

    // Create a new material for the car body with the galaxy texture
    const galaxyMaterial = React.useMemo(() => {
     return new THREE.MeshBasicMaterial({
       map: galaxyTexture,
     });
   }, [galaxyTexture]);
 
   // Replace the existing 'materials.body' with the new 'galaxyMaterial'
   materials.a8texture12__prim_env_4_spec = galaxyMaterial;
   materials.a8texture12__sec_env_4_spec = galaxyMaterial;
  }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.a8texture10} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.a8texture11__env_4_spec} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.a8texture12__env_4_spec} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.a8texture12__prim_env_4_spec} material-color={props.customColors.body}/>
        <mesh geometry={nodes.Object_6.geometry} material={materials.a8texture12__sec_env_4_spec} material-color={props.customColors.body}/>
        <mesh geometry={nodes.Object_7.geometry} material={materials.a8texture14}  />
        <mesh geometry={nodes.Object_8.geometry} material={materials.a8texture2__env_4_spec} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.a8texture3} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.a8texture5} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.a8texture6__env_4_spec} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.a8texture7} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.a8texture8__env_7_spec} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.a8texture8__spec} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.a8texture9} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.black1__env_2_spec} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.black1__env_4_spec} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.black1__env_7_spec} material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_19.geometry} material={materials.black1__env_7_spec} material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_20.geometry} material={materials.black1__spec} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.black1__spec} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.bron__env_22_spec}  material-color={props.customColors.rimsColor}/>
        <mesh geometry={nodes.Object_23.geometry} material={materials.bron__env_26_spec}  material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_24.geometry} material={materials.chrome2__env_4_trans} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.chrome2__env_6_trans} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.diavel_disk__env_3} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.hre__env_2} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.med__env_6} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.med__env_7_spec_trans} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.mirorglass__env_50_spec} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.roof} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.vehiclelights__spec} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.vehiclelights__spec_FR} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.vehiclelights__spec_RR} />
      </group>
    </group>
  )
}

useGLTF.preload('/audiA8.gltf')
