/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bmwE34.gltf 
Author: Myedsu (https://sketchfab.com/myedsu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bmw-e34-stance-style-ffe1a3a1bcb34e0bb80f1aa41c9edb46
Title: BMW E34 [stance style]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three';

function Model(props) {
  const { nodes, materials } = useGLTF('/bmwE34.gltf')
  if(props.material != "null"){
    const galaxyTexture = useLoader(TextureLoader, props.material);
  
    // Create a new material for the car body with the galaxy texture
    const galaxyMaterial = React.useMemo(() => {
      return new THREE.MeshBasicMaterial({
        map: galaxyTexture,
      });
    }, [galaxyTexture]);

    // Replace the existing 'materials.body' with the new 'galaxyMaterial'
    materials.body_paint = galaxyMaterial;
    }
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.headlight_headlight_signal_lights_0.geometry} material={materials.headlight_signal_lights} />
          <mesh geometry={nodes.headlight_headlight_0.geometry} material={materials.headlight} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.body_body_paint_0.geometry} material={materials.body_paint} material-color={props.customColors.body}/>
          <mesh geometry={nodes.body_body_plastic_0.geometry} material={materials.body_plastic} material-color={props.customColors.accesoriesColor}/>
          <mesh geometry={nodes.body_body_focus_0.geometry} material={materials.body_focus} material-color={"black"}/>
          <mesh geometry={nodes.body_win_0.geometry} material={materials.material} material-color={"black"}/>
          <mesh geometry={nodes.body_win_frame_0.geometry} material={materials.win_frame} material-color={"black"}/>
          <mesh geometry={nodes.body_body_chrome_0.geometry} material={materials.body_chrome} />
          <mesh geometry={nodes.body_mirror_0.geometry} material={materials.mirror} />
          <mesh geometry={nodes.body_body_print_0.geometry} material={materials.body_print} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.focus_int_mirror_int_focus_0.geometry} material={materials['mirror_int._focus']} />
          <mesh geometry={nodes.focus_int_tree_0.geometry} material={materials.tree} />
          <mesh geometry={nodes.focus_int_tree_rope_0.geometry} material={materials.tree_rope} />
          <mesh geometry={nodes.focus_int_mirror_int_0.geometry} material={materials['mirror_int.']} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.front_lights_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.front_lights_alum_0.geometry} material={materials.alum} />
          <mesh geometry={nodes.front_lights_Material013_0.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.front_lights_Material003_0.geometry} material={materials['Material.003']} />
        </group>
        <group position={[75.477, 33.808, 138.656]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.wheel_FL_tire004_0.geometry}  material={materials['tire.004']} material-color={"black"}/>
          <mesh geometry={nodes.wheel_FL_blt004_0.geometry} material={materials['blt.004']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_FL_disk004_0.geometry} material={materials['disk.004']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_FL_disk_paint004_0.geometry} material={materials['disk_paint.004']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_FL_bbs_tex004_0.geometry} material={materials['bbs_tex.004']} material-color={props.customColors.rimsColor}/>
        </group>
        <group position={[-75.477, 33.808, 138.656]} rotation={[-Math.PI / 2, 0, 0]} scale={100} >
          <mesh geometry={nodes.wheel_FR_tire002_0.geometry}  material={materials['tire.004']} material-color={"black"}/>
          <mesh geometry={nodes.wheel_FR_blt002_0.geometry} material={materials['blt.002']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_FR_disk002_0.geometry} material={materials['disk.002']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_FR_disk_paint002_0.geometry} material={materials['disk_paint.002']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_FR_bbs_tex002_0.geometry} material={materials['bbs_tex.002']} material-color={props.customColors.rimsColor}/>
        </group>
        <group position={[75.477, 33.808, -141.389]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.wheel_RL_tire003_0.geometry} material={materials['tire.003']} material-color={"black"}/>
          <mesh geometry={nodes.wheel_RL_blt003_0.geometry} material={materials['blt.003']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_RL_disk003_0.geometry} material={materials['disk.003']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_RL_disk_paint003_0.geometry} material={materials['disk_paint.003']} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_RL_bbs_tex003_0.geometry} material={materials['bbs_tex.003']} material-color={props.customColors.rimsColor}/>
        </group>
        <group position={[-76.425, 33.808, -141.389]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.wheel_RR_tire_0.geometry} material={materials.tire} material-color={"black"}/>
          <mesh geometry={nodes.wheel_RR_blt_0.geometry} material={materials.material_35} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_RR_disk_0.geometry} material={materials.disk} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_RR_disk_paint_0.geometry} material={materials.disk_paint} material-color={props.customColors.rimsColor}/>
          <mesh geometry={nodes.wheel_RR_bbs_tex_0.geometry} material={materials.bbs_tex} material-color={props.customColors.rimsColor}/>
        </group>
        <group position={[75.477, 34.287, 139.504]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.brake_RR_disk_brake_tr004_0.geometry} material={materials['disk_brake_tr.004']} />
          <mesh geometry={nodes.brake_RR_disk_brake004_0.geometry} material={materials['disk_brake.004']} />
        </group>
        <group position={[-75.477, 34.287, 139.504]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.brake_RL_disk_brake_tr005_0.geometry} material={materials['disk_brake_tr.005']} />
          <mesh geometry={nodes.brake_RL_disk_brake005_0.geometry} material={materials['disk_brake.005']} />
        </group>
        <group position={[75.477, 34.296, -140.571]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.brake_FR_disk_brake_tr006_0.geometry} material={materials['disk_brake_tr.006']} />
          <mesh geometry={nodes.brake_FR_disk_brake006_0.geometry} material={materials['disk_brake.006']} />
        </group>
        <group position={[-75.477, 34.296, -140.571]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.brake_FL_disk_brake_tr007_0.geometry} material={materials['disk_brake_tr.007']} />
          <mesh geometry={nodes.brake_FL_disk_brake007_0.geometry} material={materials['disk_brake.007']} />
        </group>
        <group position={[0, 37.685, -221.456]} rotation={[2.799, 0, -Math.PI]} scale={[26, 5.6, 5.826]}>
          <mesh geometry={nodes['������������������_����������������_0'].geometry} material={materials.material_47} />
          <mesh geometry={nodes['������������������_number_texture_0'].geometry} material={materials.number_texture} />
        </group>
        <group position={[0, 74.149, 237.505]} rotation={[-0.169, 0, 0]} scale={[26, 5.6, 5.826]}>
          <mesh geometry={nodes['������������������001_����������������001_0'].geometry} material={materials['.001']} />
          <mesh geometry={nodes['������������������001_number_texture001_0'].geometry} material={materials['number_texture.001']} />
        </group>
        <mesh geometry={nodes.logo_bmw_logo_0.geometry} material={materials.bmw_logo} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes['��������������_����������������002_0'].geometry} material={materials['.002']} scale={[0.329, 0.329, 1.228]} />
      </group>
    </group>
  )
}

useGLTF.preload('/bmwE34.gltf')
export default Model;