/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dodge.gltf 
Author: Gesy (https://sketchfab.com/mrgesy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dodge-challenger-2c1f18d2f0214cb7a746fc5dd2baeebe
Title: Dodge CHALLENGER
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 function Model(props) {
  const { nodes, materials } = useGLTF('/dodge.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material__295} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material__303} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material__304} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.wire_225198087} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['01___Default']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['01___Default']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Material__287} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Material__287} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Material__287} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Material__287} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Material__287} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Material__288} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Material__289} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Material__290} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Material__290} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Material__290} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Material__291} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Material__291} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Material__291} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Material__291} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.Material__291} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Material__296} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Material__296} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Material__296} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Material__297} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Material__297} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Material__298} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.Material__298} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.Material__299} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Material__300} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Material__300} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Material__301} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Material__301} />
      </group>
    </group>
  )
}

useGLTF.preload('/dodge.gltf')
export default Model;