/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dodge.gltf 
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dodge-challenger-srt-demon-sdc-54d229c2c0ff4eac8bc872f50b25e36c
Title: Dodge Challenger SRT DEMON SDC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three';

function Model(props) {
  const { nodes, materials } = useGLTF('/dodge.gltf')
  if(props.material != "null"){
    const galaxyTexture = useLoader(TextureLoader, props.material);
  
    // Create a new material for the car body with the galaxy texture
    const galaxyMaterial = React.useMemo(() => {
      return new THREE.MeshBasicMaterial({
        map: galaxyTexture,
      });
    }, [galaxyTexture]);
  
    // Replace the existing 'materials.body' with the new 'galaxyMaterial'
    materials.CARS = galaxyMaterial;
    }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.586, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.CARS}  material-color={props.customColors.body}/>
            <mesh geometry={nodes.Object_5.geometry} material={materials.Carbone} material-color={props.customColors.body}/>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
            <mesh geometry={nodes.Object_91.geometry} material={materials.GLASS} />
            <mesh geometry={nodes.Object_92.geometry} material={materials.tire} />
            <mesh geometry={nodes.Object_93.geometry} material={materials.material_16} />
            <mesh geometry={nodes.Object_94.geometry} material={materials.brakedisk} material-color={props.customColors.accesoriesColor}/>
            <mesh geometry={nodes.Object_95.geometry} material={materials.rim_second} material-color={props.customColors.rimsColor}/>
          </group>
          <mesh geometry={nodes.Object_7.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_9.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={props.customColors.accesoriesColor}/>
          <mesh geometry={nodes.Object_11.geometry} material={materials.clearglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.clearglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}  />
          <mesh geometry={nodes.Object_19.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_21.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_23.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_25.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_27.geometry} material={materials.mirror} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"red"}/>
          <mesh geometry={nodes.Object_29.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_31.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_33.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_37.geometry} material={materials.redglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.redglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={"black"}/>
          <mesh geometry={nodes.Object_47.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.orangeglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.lightglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />s
          <mesh geometry={nodes.Object_55.geometry} material={materials.GLASS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_57.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}/>
          <mesh geometry={nodes.Object_59.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}/>
          <mesh geometry={nodes.Object_61.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}/>
          <mesh geometry={nodes.Object_63.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}/>
          <mesh geometry={nodes.Object_65.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}/>
          <mesh geometry={nodes.Object_67.geometry} material={materials.carpaint_second} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} material-color={props.customColors.accesoriesColor}/>
          <mesh geometry={nodes.Object_69.geometry} material={materials.GLSS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_71.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_73.geometry} material={materials.clearglass} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_75.geometry} material={materials.GLSS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_77.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_81.geometry} material={materials.mattemetal} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_83.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_87.geometry} material={materials.interior} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_89.geometry} material={materials.interior} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.CARS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_99.geometry} material={materials.black} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_101.geometry} material={materials.CARS} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_105.geometry} material={materials.Carbone} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
          <mesh geometry={nodes.Object_107.geometry} material={materials.Carbone} position={[0, 1.814, 5.454]} scale={[1.37, 0.148, 0.024]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/dodge.gltf')
export default Model;