/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Lada.gltf 
Author: Aslan (https://sketchfab.com/Aslan_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lada-2107-55bd23c141284e758e4eacc01df14037
Title: Lada 2107
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three'; 

function Model(props) {
  const { nodes, materials } = useGLTF('/Lada.gltf')
  if(props.material != "null"){
    const galaxyTexture = useLoader(TextureLoader, props.material);
  
    // Create a new material for the car body with the galaxy texture
    const galaxyMaterial = React.useMemo(() => {
      return new THREE.MeshBasicMaterial({
        map: galaxyTexture,
      });
    }, [galaxyTexture]);
  
    // Replace the existing 'materials.body' with the new 'galaxyMaterial'
    materials.Body = galaxyMaterial;
    materials.Body2 = galaxyMaterial;
    }
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.Bumper_1} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Bumper_2} />
      </group>
      <group scale={0.165}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.F_Glass} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.F_Glass_2} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.F_Reflector} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Plastic} material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_23.geometry} material={materials.F_Lights} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.F_Turn_S} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Rear_Glass} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Rear_Reflector} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Rear_Ligts} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Rep_Signal_1} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Rep_Signal_2} />
      </group>
      <group rotation={[0, 0, -Math.PI / 2]} scale={[0.102, 1, 0.004]}>
        <mesh geometry={nodes.Object_42.geometry} material={materials['Grill.001']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Logo_Lock} />
      </group>
      <group position={[1.427, 0.293, -0.704]} rotation={[Math.PI, Math.PI / 2, 0]} scale={0.828}>
        <mesh geometry={nodes.Object_45.geometry} material={materials.Brakes} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Lock} />
      </group>
      <group position={[1.427, 0.293, 0.704]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={0.828}>
        <mesh geometry={nodes.Object_48.geometry} material={materials.Brakes} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Lock} />
      </group>
      <group position={[-1.016, 0.293, -0.704]} rotation={[0, Math.PI / 2, 0]} scale={0.824}>
        <mesh geometry={nodes.Object_51.geometry} material={materials.Brakes_2} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Brakes_details} />
      </group>
      <group position={[-1.016, 0.293, 0.688]} rotation={[0, -Math.PI / 2, 0]} scale={0.824}>
        <mesh geometry={nodes.Object_54.geometry} material={materials.Brakes_2} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.Brakes_details} />
      </group>
      <group position={[1.427, 0.293, -0.704]} rotation={[0, -1.571, 0]} scale={[0.311, 0.306, 0.306]}>
        <mesh geometry={nodes.Object_65.geometry} material={materials.KAMA_1} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.KAMA_2} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.Disc} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.Disc_details} />
      </group>
      <group position={[1.427, 0.293, 0.704]} rotation={[0, 1.571, 0]} scale={[0.311, 0.306, 0.306]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials.KAMA_1} />
        <mesh geometry={nodes.Object_71.geometry} material={materials.KAMA_2} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.Disc} />
        <mesh geometry={nodes.Object_73.geometry} material={materials.Disc_details} />
      </group>
      <group position={[-1.016, 0.293, -0.704]} rotation={[0, -1.571, 0]} scale={[0.311, 0.306, 0.306]}>
        <mesh geometry={nodes.Object_75.geometry} material={materials.KAMA_1} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.KAMA_2} />
        <mesh geometry={nodes.Object_77.geometry} material={materials.Disc} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.Disc_details} />
      </group>
      <group position={[-1.016, 0.293, 0.688]} rotation={[0, 1.571, 0]} scale={[0.311, 0.306, 0.306]}>
        <mesh geometry={nodes.Object_80.geometry} material={materials.KAMA_1} />
        <mesh geometry={nodes.Object_81.geometry} material={materials.KAMA_2} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.Disc} />
        <mesh geometry={nodes.Object_83.geometry} material={materials.Disc_details} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Body}  material-color={"red"}/>
      <mesh geometry={nodes.Object_5.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.Body} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Grill} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Body2} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Bottom} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Mirror} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Glass_2} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Radiator} rotation={[0, 0, -0.103]} scale={0.31} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['Material.039']} position={[0.622, 0.811, -0.325]} rotation={[0, 0, -0.351]} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Black_Mat} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Mirror} rotation={[0, 0, -1.042]} scale={0.01} />
      <mesh geometry={nodes.Object_57.geometry} material={materials.INTERIOR_1} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Black_Mat} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Black_Mat} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Door_Plating} />
    </group>
  )
}

useGLTF.preload('/Lada.gltf')
export default Model;