/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 mustang.gltf 
Author: WARENTERTAINMENT™ (https://sketchfab.com/WarEntertainment)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ford-mustang-2015-edition-4b1a593df06042e29dce6049b466f932
Title: Ford Mustang 2015 EDITION
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three'; 

function Model(props) {
  const { nodes, materials } = useGLTF('/mustang.gltf')
  if(props.material != "null"){
  const galaxyTexture = useLoader(TextureLoader, props.material);

  // Create a new material for the car body with the galaxy texture
  const galaxyMaterial = React.useMemo(() => {
    return new THREE.MeshBasicMaterial({
      map: galaxyTexture,
    });
  }, [galaxyTexture]);

  // Replace the existing 'materials.body' with the new 'galaxyMaterial'
  materials.CARPAINT = galaxyMaterial;
  }
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Black_Metal_Paint} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Black_Metal_Paint} />
      </group>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Object_33.geometry} material={materials.CARPAINT} material-color={props.customColors.body}/>
        <mesh geometry={nodes.Object_34.geometry} material={materials.CARPAINT} material-color={props.customColors.body}/>
      </group>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Object_46.geometry} material={materials.Black_Plastic} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Black_Plastic} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.Black_Plastic} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Black_Plastic} />
      </group>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Object_55.geometry} material={materials.Light} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.Window_Glass} />
      </group>
      <group rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01}>
        <mesh geometry={nodes.Object_62.geometry} material={materials.Rubber_Black} />
        <mesh geometry={nodes.Object_63.geometry} material={materials.Rubber_Black} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.Rubber_Black} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.Rubber_Black} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials.Black_Plastic} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Black_Metal_Paint} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.Calipers} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Chrome} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.Chrome} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.Indicator} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.Chrome} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.GlassTransparent} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.Mirror} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Brushed_Aluminum} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Light} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Black_Plastic} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.Black_Plastic} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.Window_Glass} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Chrome} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Black_Plastic} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Indicator} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.BackThingy} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_51.geometry} material={materials.Chrome} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Front_Glass} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.RedGlass} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Chrome} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/mustang.gltf')
export default Model;