/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 nissan.gltf 
Author: Tech developers (https://sketchfab.com/Deepu.Dra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-2f00a5cb6263445cbee828fabd7e0632
Title: Car
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { useLoader } from '@react-three/fiber';
import * as THREE from 'three'; 

function Model(props) {
  const { nodes, materials } = useGLTF('/nissan.gltf')
  if(props.material != "null"){
    const galaxyTexture = useLoader(TextureLoader, props.material);
  
    // Create a new material for the car body with the galaxy texture
    const galaxyMaterial = React.useMemo(() => {
      return new THREE.MeshBasicMaterial({
        map: galaxyTexture,
      });
    }, [galaxyTexture]);
  
    // Replace the existing 'materials.body' with the new 'galaxyMaterial'
    materials.body = galaxyMaterial;
    }
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BRAKES} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.INTERIOR_LOD0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.LIGHTS_lod0} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.RK_chrome} material-color={props.customColors.rimsColor}/>
        <mesh geometry={nodes.Object_8.geometry} material={materials.RK_rubber_black} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.black_glass} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['chrome.002']} material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_11.geometry} material={materials.detail_glass_red} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.emzone_padanga} /> {/* wheels*/}
        <mesh geometry={nodes.Object_13.geometry} material={materials['glass2.001']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.grille} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['inner_rim.001']} material-color={props.customColors.rimsColor}/>
        <mesh geometry={nodes.Object_16.geometry} material={materials.leather} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.mirror} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['plastic.002']} material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_19.geometry} material={materials.redglass} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.reflector} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.reverse_light_lod0} />  {/* ???*/}
        <mesh geometry={nodes.Object_22.geometry} material={materials['rim.002']} material-color={props.customColors.rimsColor}/> 
        <mesh geometry={nodes.Object_23.geometry} material={materials.undercarriage} />  {/* ???*/}
        <mesh geometry={nodes.Object_24.geometry} material={materials['window.001']} />  {/* windows*/}
        <mesh geometry={nodes.Object_25.geometry} material={materials.wood} /> {/* ???*/}
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.000']} /> {/* ???*/}
        <mesh geometry={nodes.Object_27.geometry} material={materials.NODAMAGE_LOD0}/> {/* emblem and text*/}
        <mesh geometry={nodes.Object_28.geometry} material={materials.black} /> {/* dolnica*/}
        <mesh geometry={nodes.Object_29.geometry} material={materials.body} material-color={props.customColors.body}/>
        <mesh geometry={nodes.Object_30.geometry} material={materials.body} material-color={props.customColors.body}/>
        <mesh geometry={nodes.Object_31.geometry} material={materials.bottom} /> {/* dolnica*/}
        <mesh geometry={nodes.Object_32.geometry} material={materials.chrome} />   {/* auspuh*/}
        <mesh geometry={nodes.Object_33.geometry} material={materials.digital_gauge} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.metal2} />     {/* ???*/}
        <mesh geometry={nodes.Object_35.geometry} material={materials.plastic2} />   {/* ???*/}
        <mesh geometry={nodes.Object_36.geometry} material={materials.plastic2} />   {/* ???*/}
        <mesh geometry={nodes.Object_37.geometry} material={materials.plastic2} material-color={props.customColors.accesoriesColor}/>
        <mesh geometry={nodes.Object_38.geometry} material={materials.rubber}  />  {/* chistachki*/}
        <mesh geometry={nodes.Object_39.geometry} material={materials['rubber_trim.002']} /> {/* ???*/}
      </group>
    </group>
  )
}

useGLTF.preload('/nissan.gltf')
export default Model;